apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image-venafi-key
  annotations:
    policies.kyverno.io/category: Image Verification
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image-venafi-key
      context:
        - name: venaficonfigmap
#Below configmap values below should match the ones in CR yaml imagekey.yaml. More info: https://github.com/nirmata/kyverno-charts/tree/main/charts/venafi-adapter#test-a-sample-policy
          configMap:
            name: venaficm
            namespace: nirmata-venafi-adapter
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - imageReferences:
            - docker.io/*
#Update the above registry reference to the appropriate registry
          attestors:
            - count: 1
              entries:
                - certificates:
                    certChain: "{{venaficonfigmap.data.key1}}"
#Above configmap key should match the ones in CR yaml imagekey.yaml. More info: https://github.com/nirmata/kyverno-charts/tree/main/charts/venafi-adapter#test-a-sample-policy
